import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Header from "@/components/Header";
import {Providers} from "../context/UIProvider";
import AuthProvider from "@/context/AuthProvider";
import { SocketProvider } from "@/context/SocketProvider";
import { ScrollProvider } from "@/context/ScrollProvider";


// import type { Viewport } from 'next'
 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ScrollProvider>
          <AuthProvider>
            <SocketProvider url={process.env.CUSTOM_SERVER_URL||'http://localhost:8000'}>
              <Providers>
                {children}
              </Providers> 
            </SocketProvider>
          </AuthProvider>
        </ScrollProvider>
      </body>
    </html>
  );
}
